# Site settings
title: Mingism / 明主意
description: >- # this means to ignore newlines until "baseurl:"
  Ming's Blog
github_username:  YemingLakeForest

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!--MORE-->"

# Use Github Flavored Markdown
kramdown:
  input: GFM